### ISSUE TITLE
URL Broken with the extension. Except the homepage.

### ISSUE THREAD

**Issue by shawny43** [FriendsOfFlarum/html-errors#12] opened 2021-08-03 00:13 UTC
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

Enter or click a URL that come directly a page, topic or blog made you into error 404.
Sharing is not fix beacause he use a url too.

The only url i can enter is my home page. 

**Steps to Reproduce**
1. Go to 'Specific url, exemple: https://shawny43.flarum.cloud/p/7-Exemple/'

Is the only step. Sharing url or not is the same error anyways.

**Expected Behavior**

**Screenshots**

All my screens and discutions is inside the topic: https://discuss.flarum.org/d/28412-url-broken-everywhere-except-the-home-url/5

**Environment**
- Flarum version: 1.0.4
- Extension version: 1.0.0
- Website URL: https://shawny43.flarum.cloud
- Webserver: FreeFlarum
- Hosting environment: Freeflarum
- PHP version: 8.0.9
- Browser: Firefox, Edge, Chrome, Brave, etc.

```
Output of "php flarum info", run this in terminal in your Flarum directory.

I can't only Freeflarum team can do this.
```

**Possible solution(s)**

Simply disable the Extension. No solutions yet.

**Additional Context**

**Comment by clarkwinkelmann** [comment] 2021-08-03 06:42
I'm not able to reproduce.

Can you share which of the status code was customized, and what your custom HTML was?

Can you maybe try to re-enable the extensions in a different order and/or clear the cache again to see if the issue goes away?

Your example page seems to be a real 404 error for guests so it would be normal for it to be handled by this extension. I suppose the extension is no longer enabled on your forum so I probably can no longer experience the error there anyway.

The way this extension is working, it hooks into Flarum error handler so the extension shouldn't have any effect until Flarum tries to render an error page, so it's very unlikely to be the cause of the error in the first place.

**Comment by shawny43** [comment] 2021-08-04 01:13
Is normal, i disabled it beacause is make errors for no reasons. You want to me to enable it?

**Comment by clarkwinkelmann** [comment] 2021-08-04 10:57
Yes if you could enable it again and do the few checks I describe above that would be great!

Otherwise I'm really not sure how we're going to figure out what's wrong. As I said above it doesn't look like an error caused by this extension, but more like another error or misconfiguration that's amplified by the error page being replaced with this extension.

In particular I'd need to know which status code you replaced. In the screenshot on the forum I suppose you replaced the 404 page, but did you replace another as well?

**Comment by shawny43** [comment] 2021-08-06 22:00
I try to get all my extensions including the error custom one. I did reset a bit ago due a extension that broke entirely my admin panel. I gonna tell you if everything is ready.

**Comment by shawny43** [comment] 2021-08-06 22:03
Idk whats happend but when i clear everything. And yeah i got help from the FF staff who clear cache due to the admin panel problems. But is fixed by himself. Idk why

**Comment by clarkwinkelmann** [comment] 2021-08-15 16:32
I'm going to close this issue since we don't have enough information to confirm this extension is causing the problem.

Please let us know if this happens again or if you find more details, we'll take a look again :wink:

**Closed as completed by clarkwinkelmann** 2021-08-15 16:32 UTC
Labels: bug
